### ISSUE TITLE
in 1.16.5, pistons crash my game when loading quickcarpet.

### ISSUE THREAD

**Issue by fooeyround** [Andrews54757/tweakfork#25]
[17:13:57] [main/WARN]: @ModifyConstant conflict. Skipping mixins.tweakeroo.json:MixinCloneCommand->@ModifyConstant::getBlockCountLimit(I)I with priority 999, already redirected by quickcarpet.mixins.json:commands.CloneCommandMixin->@ModifyConstant::fillLimit(I)I with priority 1000
[17:13:57] [main/WARN]: @ModifyConstant conflict. Skipping mixins.tweakeroo.json:MixinCloneCommand->@ModifyConstant::getBlockCountLimit(I)I with priority 999, already redirected by quickcarpet.mixins.json:commands.CloneCommandMixin->@ModifyConstant::fillLimit(I)I with priority 1000
[17:13:57] [main/WARN]: @ModifyConstant conflict. Skipping mixins.tweakeroo.json:MixinFillCommand->@ModifyConstant::getBlockCountLimit(I)I with priority 999, already redirected by quickcarpet.mixins.json:commands.FillCommandMixin->@ModifyConstant::fillLimit(I)I with priority 1000
[17:13:57] [main/WARN]: @ModifyConstant conflict. Skipping mixins.tweakeroo.json:MixinFillCommand->@ModifyConstant::getBlockCountLimit(I)I with priority 999, already redirected by quickcarpet.mixins.json:commands.FillCommandMixin->@ModifyConstant::fillLimit(I)I with priority 1000
[17:13:58] [main/WARN]: Ambiguity between arguments [teleport, destination] and [teleport, targets] with inputs: [Player, 0123, 

[17:14:17] [Server thread/WARN]: @ModifyConstant conflict. Skipping mixins.tweakeroo.json:MixinPistonHandler->@ModifyConstant::modifyPushLimitPistorderMod(I)I with priority 990, already redirected by quickcarpet.mixins.json:piston.PistonHandlerMixin->@ModifyConstant::adjustPushLimit(I)I with priority 1000
[17:14:17] [Server thread/WARN]: @ModifyConstant conflict. Skipping mixins.tweakeroo.json:MixinPistonHandler->@ModifyConstant::modifyPushLimitPistorderMod(I)I with priority 990, already redirected by quickcarpet.mixins.json:piston.PistonHandlerMixin->@ModifyConstant::adjustPushLimit(I)I with priority 1000
[17:14:17] [Server thread/WARN]: @ModifyConstant conflict. Skipping mixins.tweakeroo.json:MixinPistonHandler->@ModifyConstant::modifyPushLimitPistorderMod(I)I with priority 990, already redirected by quickcarpet.mixins.json:piston.PistonHandlerMixin->@ModifyConstant::adjustPushLimit(I)I with priority 1000

then crashes:
[17:15:45] [Server thread/WARN]: @ModifyConstant conflict. Skipping mixins.tweakeroo.json:MixinPistonHandler->@ModifyConstant::modifyPushLimitPistorderMod(I)I with priority 990, already redirected by quickcarpet.mixins.json:piston.PistonHandlerMixin->@ModifyConstant::adjustPushLimit(I)I with priority 1000
[17:15:45] [Server thread/WARN]: @ModifyConstant conflict. Skipping mixins.tweakeroo.json:MixinPistonHandler->@ModifyConstant::modifyPushLimitPistorderMod(I)I with priority 990, already redirected by quickcarpet.mixins.json:piston.PistonHandlerMixin->@ModifyConstant::adjustPushLimit(I)I with priority 1000
[17:15:45] [Server thread/WARN]: @ModifyConstant conflict. Skipping mixins.tweakeroo.json:MixinPistonHandler->@ModifyConstant::modifyPushLimitPistorderMod(I)I with priority 990, already redirected by quickcarpet.mixins.json:piston.PistonHandlerMixin->@ModifyConstant::adjustPushLimit(I)I with priority 1000
[17:15:45] [Server thread/ERROR]: Encountered an unexpected exception
org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208) ~[sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178) ~[sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23) ~[fabric-loader-0.11.6.jar:0.9.4+mixin.0.8.2]
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:162) ~[fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:154) ~[fabric-loader-0.11.6.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_51]
	at net.minecraft.class_2665.method_11483(class_2665.java:116) ~[intermediary-fabric-loader-0.11.6-1.16.5.jar:?]
	at net.minecraft.class_2665.method_9615(class_2665.java:101) ~[intermediary-fabric-loader-0.11.6-1.16.5.jar:?]
	at net.minecraft.class_4970$class_4971.method_26182(class_4970.java:866) ~[intermediary-fabric-loader-0.11.6-1.16.5.jar:?]
	at net.minecraft.class_2818.redirect$zil000$onAdded(class_2818.java:926) ~[intermediary-fabric-loader-0.11.6-1.16.5.jar:?]
	at net.minecraft.class_2818.method_12010(class_2818.java:293) ~[intermediary-fabric-loader-0.11.6-1.16.5.jar:?]
	at net.minecraft.class_1937.redirect$zik000$setBlockStateInChunk(class_1937.java:1718) ~[intermediary-fabric-loader-0.11.6-1.16.5.jar:?]
	at net.minecraft.class_1937.method_30092(class_1937.java:231) ~[intermediary-fabric-loader-0.11.6-1.16.5.jar:?]
	at net.minecraft.class_1937.method_8652(class_1937.java:217) ~[intermediary-fabric-loader-0.11.6-1.16.5.jar:?]
	at net.minecraft.class_1747.method_7708(class_1747.java:151) ~[intermediary-fabric-loader-0.11.6-1.16.5.jar:?]
	at net.minecraft.class_1747.method_7712(class_1747.java:68) ~[intermediary-fabric-loader-0.11.6-1.16.5.jar:?]
	at net.minecraft.class_1747.method_7884(class_1747.java:43) ~[intermediary-fabric-loader-0.11.6-1.16.5.jar:?]
	at net.minecraft.class_1799.method_7981(class_1799.java:227) ~[intermediary-fabric-loader-0.11.6-1.16.5.jar:?]
	at net.minecraft.class_3225.method_14262(class_3225.java:345) ~[intermediary-fabric-loader-0.11.6-1.16.5.jar:?]
	at net.minecraft.class_3244.method_12046(class_3244.java:1040) ~[intermediary-fabric-loader-0.11.6-1.16.5.jar:?]
	at net.minecraft.class_2885.method_12547(class_2885.java:36) ~[intermediary-fabric-loader-0.11.6-1.16.5.jar:?]
	at net.minecraft.class_2885.method_11054(class_2885.java:10) ~[intermediary-fabric-loader-0.11.6-1.16.5.jar:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:21) ~[intermediary-fabric-loader-0.11.6-1.16.5.jar:?]
	at net.minecraft.class_2600$$Lambda$6520/1742062776.run(Unknown Source) ~[?:?]
	at net.minecraft.class_3738.run(class_3738.java:18) ~[intermediary-fabric-loader-0.11.6-1.16.5.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:144) ~[intermediary-fabric-loader-0.11.6-1.16.5.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[intermediary-fabric-loader-0.11.6-1.16.5.jar:?]
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:761) ~[intermediary-fabric-loader-0.11.6-1.16.5.jar:?]
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:155) ~[intermediary-fabric-loader-0.11.6-1.16.5.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:118) ~[intermediary-fabric-loader-0.11.6-1.16.5.jar:?]
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:743) ~[intermediary-fabric-loader-0.11.6-1.16.5.jar:?]
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:737) ~[intermediary-fabric-loader-0.11.6-1.16.5.jar:?]
	at net.minecraft.class_1255.method_18857(class_1255.java:127) ~[intermediary-fabric-loader-0.11.6-1.16.5.jar:?]
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:722) ~[intermediary-fabric-loader-0.11.6-1.16.5.jar:?]
	at net.minecraft.server.MinecraftServer.handler$zlf000$modifiedRunLoop(MinecraftServer.java:4276) ~[intermediary-fabric-loader-0.11.6-1.16.5.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:651) [intermediary-fabric-loader-0.11.6-1.16.5.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) [intermediary-fabric-loader-0.11.6-1.16.5.jar:?]
	at net.minecraft.server.MinecraftServer$$Lambda$5594/918585558.run(Unknown Source) [intermediary-fabric-loader-0.11.6-1.16.5.jar:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Constant modifier method modifyPushLimitPistorderMod(I)I in mixins.tweakeroo.json:MixinPistonHandler failed injection check, (0/3) succeeded. Scanned 1 target(s). Using refmap tweakfork-fabric-1.16.4-refmap.json
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:408) ~[sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1291) ~[sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1042) ~[sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395) ~[sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320) ~[sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345) ~[sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:569) ~[sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351) ~[sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2]
	... 39 more
[17:15:45] [Server thread/ERROR]: This crash report has been saved to: C:\Users\Administrator\AppData\Roaming\.oldertech\crash-reports\crash-2021-10-03_17.15.45-server.txt
[17:15:45] [Server thread/INFO]: Unregistering com.sk89q.worldedit.fabric.FabricPlatform from WorldEdit
[17:15:45] [Server thread/INFO]: Stopping server
[17:15:45] [Server thread/INFO]: Saving players

**Comment by Andrews54757** [comment]
Removed pistorder so its fixed.
