### ISSUE TITLE
Game crashes when invoking `tweakInventoryPreview` while looking at a block out of reach or at the sky

### ISSUE THREAD

**Issue by xane256** [Andrews54757/tweakfork#60]
https://github.com/Andrews54757/tweakfork/blob/e6d8e2aa0215613f9e3ec9273f58411ec3ef6fb8/src/main/java/fi/dy/masa/tweakeroo/renderer/RenderUtils.java#L144C9-L144C9

The game crash log begins with this info:
```
---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 2023-11-02 13:39:51
Description: Unexpected error

java.lang.NullPointerException: Cannot invoke "net.minecraft.class_239.method_17783()" because "trace" is null
	at fi.dy.masa.tweakeroo.renderer.RenderUtils.renderInventoryOverlay(RenderUtils.java:144)
	at fi.dy.masa.tweakeroo.event.RenderHandler.onRenderGameOverlayPost(RenderHandler.java:46)
	at fi.dy.masa.malilib.event.RenderEventHandler.onRenderGameOverlayPost(RenderEventHandler.java:69)
	at net.minecraft.class_329.handler$fco000$malilib$onGameOverlayPost(class_329.java:4376)
	at net.minecraft.class_329.method_1753(class_329.java:370)
	at net.minecraft.class_757.method_3192(class_757.java:926)
	at net.minecraft.class_310.method_1523(class_310.java:1219)
	at net.minecraft.class_310.method_1514(class_310.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)
```

I can send more if needed

**Comment by DarkCows** [comment]
@xane256 
I fixed this issue in my fork of tweakfork
the mod now verifies that trace doesn't equal null
https://github.com/DarkCows/tweakfork-fork/releases/tag/fabric-1.20%2F21-3
